s = input('Введите строку: ')

print('a.', s[2])
print('b.', s[-2])
print('c.', s[:5])
print('d.', s[:len(s)-2])
print('e.', s[::2])
print('f.', s[1::2])
print('g.', s[::-1])
print('h.', s[-1::-2])
print('i.', len(s))
